//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smarthome;

public interface DecorativeLight extends Light
{
    void setPattern(Pattern pattern, com.zeroc.Ice.Current current)
        throws InvalidInput;

    Pattern getPattern(com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::smarthome::DecorativeLight",
        "::smarthome::Light",
        "::smarthome::ProgrammableDevice",
        "::smarthome::SchedulableDevice"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::smarthome::DecorativeLight";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_setPattern(DecorativeLight obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        Pattern iceP_pattern;
        iceP_pattern = Pattern.ice_read(istr);
        inS.endReadParams();
        obj.setPattern(iceP_pattern, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPattern(DecorativeLight obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        Pattern ret = obj.getPattern(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Pattern.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "clearWorkSchedule",
        "getPattern",
        "getStatus",
        "getWorkMode",
        "getWorkSchedule",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "setPattern",
        "setStatus",
        "setWorkMode",
        "setWorkSchedule"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return SchedulableDevice._iceD_clearWorkSchedule(this, in, current);
            }
            case 1:
            {
                return _iceD_getPattern(this, in, current);
            }
            case 2:
            {
                return Light._iceD_getStatus(this, in, current);
            }
            case 3:
            {
                return ProgrammableDevice._iceD_getWorkMode(this, in, current);
            }
            case 4:
            {
                return SchedulableDevice._iceD_getWorkSchedule(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 9:
            {
                return _iceD_setPattern(this, in, current);
            }
            case 10:
            {
                return Light._iceD_setStatus(this, in, current);
            }
            case 11:
            {
                return ProgrammableDevice._iceD_setWorkMode(this, in, current);
            }
            case 12:
            {
                return SchedulableDevice._iceD_setWorkSchedule(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
