//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smarthome;

public class FridgeStatus implements java.lang.Cloneable,
                                     java.io.Serializable
{
    public int temperature;

    public int humidity;

    public boolean doorClosed;

    public FridgeStatus()
    {
    }

    public FridgeStatus(int temperature, int humidity, boolean doorClosed)
    {
        this.temperature = temperature;
        this.humidity = humidity;
        this.doorClosed = doorClosed;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FridgeStatus r = null;
        if(rhs instanceof FridgeStatus)
        {
            r = (FridgeStatus)rhs;
        }

        if(r != null)
        {
            if(this.temperature != r.temperature)
            {
                return false;
            }
            if(this.humidity != r.humidity)
            {
                return false;
            }
            if(this.doorClosed != r.doorClosed)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::smarthome::FridgeStatus");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, temperature);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, humidity);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, doorClosed);
        return h_;
    }

    public FridgeStatus clone()
    {
        FridgeStatus c = null;
        try
        {
            c = (FridgeStatus)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.temperature);
        ostr.writeInt(this.humidity);
        ostr.writeBool(this.doorClosed);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.temperature = istr.readInt();
        this.humidity = istr.readInt();
        this.doorClosed = istr.readBool();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, FridgeStatus v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public FridgeStatus ice_read(com.zeroc.Ice.InputStream istr)
    {
        FridgeStatus v = new FridgeStatus();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<FridgeStatus> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, FridgeStatus v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(9);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<FridgeStatus> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(FridgeStatus.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final FridgeStatus _nullMarshalValue = new FridgeStatus();

    /** @hidden */
    public static final long serialVersionUID = -4905960454619813756L;
}
