//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smarthome;

/**
 * Helper class for marshaling/unmarshaling GroceriesList.
 **/
public final class GroceriesListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, GroceriesItem[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                GroceriesItem.ice_write(ostr, v[i0]);
            }
        }
    }

    public static GroceriesItem[] read(com.zeroc.Ice.InputStream istr)
    {
        final GroceriesItem[] v;
        final int len0 = istr.readAndCheckSeqSize(2);
        v = new GroceriesItem[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = GroceriesItem.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GroceriesItem[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, GroceriesItem[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            GroceriesListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<GroceriesItem[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            GroceriesItem[] v;
            v = GroceriesListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
