//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smarthome;

public class GroceriesItem implements java.lang.Cloneable,
                                      java.io.Serializable
{
    public String name;

    public String quantity;

    public GroceriesItem()
    {
        this.name = "";
        this.quantity = "";
    }

    public GroceriesItem(String name, String quantity)
    {
        this.name = name;
        this.quantity = quantity;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        GroceriesItem r = null;
        if(rhs instanceof GroceriesItem)
        {
            r = (GroceriesItem)rhs;
        }

        if(r != null)
        {
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.quantity != r.quantity)
            {
                if(this.quantity == null || r.quantity == null || !this.quantity.equals(r.quantity))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::smarthome::GroceriesItem");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, quantity);
        return h_;
    }

    public GroceriesItem clone()
    {
        GroceriesItem c = null;
        try
        {
            c = (GroceriesItem)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.name);
        ostr.writeString(this.quantity);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.name = istr.readString();
        this.quantity = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, GroceriesItem v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public GroceriesItem ice_read(com.zeroc.Ice.InputStream istr)
    {
        GroceriesItem v = new GroceriesItem();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GroceriesItem> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, GroceriesItem v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<GroceriesItem> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(GroceriesItem.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final GroceriesItem _nullMarshalValue = new GroceriesItem();

    /** @hidden */
    public static final long serialVersionUID = -3343490954680465531L;
}
