//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smarthome;

public interface SchedulableDevice extends ProgrammableDevice
{
    void setWorkSchedule(DayOfTheWeek day, WorkTimeInterval time, com.zeroc.Ice.Current current)
        throws InvalidInput;

    java.util.Map<DayOfTheWeek, WorkTimeInterval> getWorkSchedule(DayOfTheWeek day, com.zeroc.Ice.Current current);

    void clearWorkSchedule(DayOfTheWeek day, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::smarthome::ProgrammableDevice",
        "::smarthome::SchedulableDevice"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::smarthome::SchedulableDevice";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_setWorkSchedule(SchedulableDevice obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        DayOfTheWeek iceP_day;
        WorkTimeInterval iceP_time;
        iceP_day = DayOfTheWeek.ice_read(istr);
        iceP_time = WorkTimeInterval.ice_read(istr);
        inS.endReadParams();
        obj.setWorkSchedule(iceP_day, iceP_time, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getWorkSchedule(SchedulableDevice obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        DayOfTheWeek iceP_day;
        iceP_day = DayOfTheWeek.ice_read(istr);
        inS.endReadParams();
        java.util.Map<DayOfTheWeek, WorkTimeInterval> ret = obj.getWorkSchedule(iceP_day, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        WorkTimeHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_clearWorkSchedule(SchedulableDevice obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        DayOfTheWeek iceP_day;
        iceP_day = DayOfTheWeek.ice_read(istr);
        inS.endReadParams();
        obj.clearWorkSchedule(iceP_day, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "clearWorkSchedule",
        "getWorkMode",
        "getWorkSchedule",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "setWorkMode",
        "setWorkSchedule"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_clearWorkSchedule(this, in, current);
            }
            case 1:
            {
                return ProgrammableDevice._iceD_getWorkMode(this, in, current);
            }
            case 2:
            {
                return _iceD_getWorkSchedule(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 7:
            {
                return ProgrammableDevice._iceD_setWorkMode(this, in, current);
            }
            case 8:
            {
                return _iceD_setWorkSchedule(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
