//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smarthome;

public interface SchedulableDevicePrx extends ProgrammableDevicePrx
{
    default void setWorkSchedule(DayOfTheWeek day, WorkTimeInterval time)
        throws InvalidInput
    {
        setWorkSchedule(day, time, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setWorkSchedule(DayOfTheWeek day, WorkTimeInterval time, java.util.Map<String, String> context)
        throws InvalidInput
    {
        try
        {
            _iceI_setWorkScheduleAsync(day, time, context, true).waitForResponseOrUserEx();
        }
        catch(InvalidInput ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> setWorkScheduleAsync(DayOfTheWeek day, WorkTimeInterval time)
    {
        return _iceI_setWorkScheduleAsync(day, time, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setWorkScheduleAsync(DayOfTheWeek day, WorkTimeInterval time, java.util.Map<String, String> context)
    {
        return _iceI_setWorkScheduleAsync(day, time, context, false);
    }

    /**
     * @hidden
     * @param iceP_day -
     * @param iceP_time -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setWorkScheduleAsync(DayOfTheWeek iceP_day, WorkTimeInterval iceP_time, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setWorkSchedule", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_setWorkSchedule);
        f.invoke(true, context, null, ostr -> {
                     DayOfTheWeek.ice_write(ostr, iceP_day);
                     WorkTimeInterval.ice_write(ostr, iceP_time);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setWorkSchedule =
    {
        InvalidInput.class
    };

    default java.util.Map<DayOfTheWeek, WorkTimeInterval> getWorkSchedule(DayOfTheWeek day)
    {
        return getWorkSchedule(day, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default java.util.Map<DayOfTheWeek, WorkTimeInterval> getWorkSchedule(DayOfTheWeek day, java.util.Map<String, String> context)
    {
        return _iceI_getWorkScheduleAsync(day, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<DayOfTheWeek, WorkTimeInterval>> getWorkScheduleAsync(DayOfTheWeek day)
    {
        return _iceI_getWorkScheduleAsync(day, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<DayOfTheWeek, WorkTimeInterval>> getWorkScheduleAsync(DayOfTheWeek day, java.util.Map<String, String> context)
    {
        return _iceI_getWorkScheduleAsync(day, context, false);
    }

    /**
     * @hidden
     * @param iceP_day -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.util.Map<DayOfTheWeek, WorkTimeInterval>> _iceI_getWorkScheduleAsync(DayOfTheWeek iceP_day, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.util.Map<DayOfTheWeek, WorkTimeInterval>> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getWorkSchedule", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     DayOfTheWeek.ice_write(ostr, iceP_day);
                 }, istr -> {
                     java.util.Map<DayOfTheWeek, WorkTimeInterval> ret;
                     ret = WorkTimeHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void clearWorkSchedule(DayOfTheWeek day)
    {
        clearWorkSchedule(day, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void clearWorkSchedule(DayOfTheWeek day, java.util.Map<String, String> context)
    {
        _iceI_clearWorkScheduleAsync(day, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> clearWorkScheduleAsync(DayOfTheWeek day)
    {
        return _iceI_clearWorkScheduleAsync(day, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> clearWorkScheduleAsync(DayOfTheWeek day, java.util.Map<String, String> context)
    {
        return _iceI_clearWorkScheduleAsync(day, context, false);
    }

    /**
     * @hidden
     * @param iceP_day -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_clearWorkScheduleAsync(DayOfTheWeek iceP_day, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "clearWorkSchedule", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(false, context, null, ostr -> {
                     DayOfTheWeek.ice_write(ostr, iceP_day);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SchedulableDevicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), SchedulableDevicePrx.class, _SchedulableDevicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SchedulableDevicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), SchedulableDevicePrx.class, _SchedulableDevicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SchedulableDevicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), SchedulableDevicePrx.class, _SchedulableDevicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SchedulableDevicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), SchedulableDevicePrx.class, _SchedulableDevicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static SchedulableDevicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, SchedulableDevicePrx.class, _SchedulableDevicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static SchedulableDevicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, SchedulableDevicePrx.class, _SchedulableDevicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default SchedulableDevicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (SchedulableDevicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default SchedulableDevicePrx ice_adapterId(String newAdapterId)
    {
        return (SchedulableDevicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default SchedulableDevicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (SchedulableDevicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default SchedulableDevicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (SchedulableDevicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default SchedulableDevicePrx ice_invocationTimeout(int newTimeout)
    {
        return (SchedulableDevicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default SchedulableDevicePrx ice_connectionCached(boolean newCache)
    {
        return (SchedulableDevicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default SchedulableDevicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (SchedulableDevicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SchedulableDevicePrx ice_secure(boolean b)
    {
        return (SchedulableDevicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default SchedulableDevicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (SchedulableDevicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SchedulableDevicePrx ice_preferSecure(boolean b)
    {
        return (SchedulableDevicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default SchedulableDevicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (SchedulableDevicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default SchedulableDevicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (SchedulableDevicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default SchedulableDevicePrx ice_collocationOptimized(boolean b)
    {
        return (SchedulableDevicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default SchedulableDevicePrx ice_twoway()
    {
        return (SchedulableDevicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default SchedulableDevicePrx ice_oneway()
    {
        return (SchedulableDevicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default SchedulableDevicePrx ice_batchOneway()
    {
        return (SchedulableDevicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default SchedulableDevicePrx ice_datagram()
    {
        return (SchedulableDevicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default SchedulableDevicePrx ice_batchDatagram()
    {
        return (SchedulableDevicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default SchedulableDevicePrx ice_compress(boolean co)
    {
        return (SchedulableDevicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default SchedulableDevicePrx ice_timeout(int t)
    {
        return (SchedulableDevicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default SchedulableDevicePrx ice_connectionId(String connectionId)
    {
        return (SchedulableDevicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default SchedulableDevicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (SchedulableDevicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::smarthome::SchedulableDevice";
    }
}
