//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package smarthome;
/**
 * Helper class for marshaling/unmarshaling WorkTime.
 **/

public final class WorkTimeHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, java.util.Map<DayOfTheWeek, WorkTimeInterval> v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.size());
            for(java.util.Map.Entry<DayOfTheWeek, WorkTimeInterval> e : v.entrySet())
            {
                DayOfTheWeek.ice_write(ostr, e.getKey());
                WorkTimeInterval.ice_write(ostr, e.getValue());
            }
        }
    }

    public static java.util.Map<DayOfTheWeek, WorkTimeInterval> read(com.zeroc.Ice.InputStream istr)
    {
        java.util.Map<DayOfTheWeek, WorkTimeInterval> v;
        v = new java.util.HashMap<smarthome.DayOfTheWeek, smarthome.WorkTimeInterval>();
        int sz0 = istr.readSize();
        for(int i0 = 0; i0 < sz0; i0++)
        {
            DayOfTheWeek key;
            key = DayOfTheWeek.ice_read(istr);
            WorkTimeInterval value;
            value = WorkTimeInterval.ice_read(istr);
            v.put(key, value);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<java.util.Map<DayOfTheWeek, WorkTimeInterval>> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Map<DayOfTheWeek, WorkTimeInterval> v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            WorkTimeHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<java.util.Map<DayOfTheWeek, WorkTimeInterval>> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            java.util.Map<DayOfTheWeek, WorkTimeInterval> v;
            v = WorkTimeHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
